INSERT INTO security_permission (ID, DESCRIPTION, PERMISSION_ID ) VALUES (3,'ROLE_ADMIN','ROLE_ADMIN' );


INSERT INTO security_group (ID, NAME ) VALUES (3,'ADMIN' );

INSERT INTO securitygroup_security_permissions (SECURITYGROUP, SECURITYPERMISSIONS )VALUES (3,3);

insert into `person_role` (`ID`, `DOMAIN_ROLE`, `DATE_OF_BIRTH`, `EMAIL`, `GENDER`, `FIRST_NAME`, `LAST_NAME`, `MIDDLE_NAME`) values('1','ADMIN',NULL,'admin@gmail.com',NULL,'The Administrator',NULL,NULL);


INSERT INTO user_login (ID, HOME_PAGE_VIEW, IS_ENABLED, NUMBER_OF_FAILED_LOGIN_ATTEMPTS,
PASSWORD, USERNAME,IS_ACCOUNT_NON_LOCKED,PERSONROLE ) VALUES (1,'ADMIN_HOME_PAGE',1,0,'7b06d1ebd7e796e73e909a4e0be1b07a568519d0','admin@gmail.com',1,'1');


INSERT INTO userlogin_security_groups (USERLOGIN, SECURITYGROUPS ) VALUES (1,3 );

